title: "Daear Consulting, LLC"
description: "Sovereignty-Aligned Data Infrastructure | Tribal Data Sovereignty | Geospatial Analytics | AI-Integrated Governance"
url: "https://daearconsulting.github.io"
baseurl: ""
lang: "en-US"
logo: "/assets/images/logo.png" # optional but helps SEO preview cards

social:
  name: "Daear Consulting, LLC"
  links:
    - https://www.linkedin.com/in/lillyjones3/
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

repository: "daearconsulting/daear-consulting"

author:
  name: "Daear Consulting, LLC"
  email: "daearconsulting@gmail.com"

minimal_mistakes_skin: "default"

breadcrumbs: false
search: false

nav:
  - title: "About"
    url: /about/
  - title: "Services"
    url: /services/
  - title: "Contact"
    url: /contact/
  - title: "Case Studies"
    url: /case-studies/

footer:
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:daearconsulting@gmail.com"
